/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.jugador;
import Model.partida;
import dao.daoGeneric;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author AluCiclesGS1
 */
public class DialogCombat extends javax.swing.JDialog {
    private jugador jug1;
    private jugador jug2;
    private javax.swing.Timer animacioTimer;
    private int frameAnimacio = 0;
    private String[] espases = {"⚔️", "🗡️", "⚔️", "💥"};


    private void carregarTipusPartida() {
        comboTipus.addItem("Lliga");
        comboTipus.addItem("Torneig");
        comboTipus.addItem("Amistos");
    }
    
    /**
     * Creates new form DialogCombat
     */
    public DialogCombat(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        carregarTipusPartida();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboTipus = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        LabelJug1 = new javax.swing.JLabel();
        LabelJug2 = new javax.swing.JLabel();
        lblAnimacio = new javax.swing.JLabel();
        btnSimularCombat = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblGuanyador = new javax.swing.JLabel();
        lblResultat = new javax.swing.JLabel();
        lblTemps = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 380));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Simulador de combat");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tipus de partida:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTipus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboTipus, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 340, 50));

        LabelJug1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelJug1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJug1.setText("jLabel3");

        LabelJug2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelJug2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJug2.setText("jLabel3");

        lblAnimacio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnimacio.setText("⚔️");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(LabelJug1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAnimacio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(LabelJug2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelJug1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelJug2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAnimacio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 340, 100));

        btnSimularCombat.setText("Simular combat");
        btnSimularCombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularCombatActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimularCombat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 120, 30));

        lblGuanyador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblGuanyador.setText("Guanyador:");

        lblResultat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblResultat.setText("Resultat:");

        lblTemps.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTemps.setText("Temps:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGuanyador, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTemps, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGuanyador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTemps, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 300, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimularCombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularCombatActionPerformed
        // Buscar 2 jugadors de nivell similar
        List<jugador> parella = daoGeneric.getInstance().trobarParellaJugadors();
        
        if (parella == null || parella.size() < 2) {
            JOptionPane.showMessageDialog(this, "No hi ha prou jugadors", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        jug1 = parella.get(0);
        jug2 = parella.get(1);
        
        // Mostrar jugadors
        LabelJug1.setText(jug1.getNom());
        LabelJug2.setText(jug2.getNom());
        lblResultat.setText("");
        lblTemps.setText("");
        lblGuanyador.setText("");
        
        btnSimularCombat.setEnabled(false);
        frameAnimacio = 0;
        
        animacioTimer = new javax.swing.Timer(300, e -> {
            lblAnimacio.setText(espases[frameAnimacio % espases.length]);
            frameAnimacio++;
            
            if (frameAnimacio >= 12) {
                animacioTimer.stop();
                mostrarResultat();
                btnSimularCombat.setEnabled(true);
            }
        });
        
        animacioTimer.start();
    }//GEN-LAST:event_btnSimularCombatActionPerformed
    
    private void mostrarResultat() {
        Random rand = new Random();
        
        // Resultat random
        jugador guanyador = rand.nextBoolean() ? jug1 : jug2;
        jugador perdedor = guanyador.equals(jug1) ? jug2 : jug1;
        
        // Generar marcador
        int puntsGuanyador = rand.nextInt(3) + 1;
        int puntsPerdedor = rand.nextInt(puntsGuanyador);
        String resultat = puntsGuanyador + "-" + puntsPerdedor;
        
        int minuts = rand.nextInt(5) + 1;
        int segons = rand.nextInt(60);
        String temps = minuts + ":" + String.format("%02d", segons);
        String tipus = (String) comboTipus.getSelectedItem();
        
        lblGuanyador.setText("Guanyador: " + guanyador.getNom());
        lblResultat.setText("Resultat: " + resultat);
        lblTemps.setText("Temps: " + temps + " min");
        
        partida p = new partida();
        p.setIdJug1(jug1.getId());
        p.setIdJug2(jug2.getId());
        p.setResultat(resultat);
        p.setTemps(temps);
        p.setTipus(tipus);
        
        daoGeneric.getInstance().create(p);      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCombat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCombat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCombat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCombat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCombat dialog = new DialogCombat(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelJug1;
    private javax.swing.JLabel LabelJug2;
    private javax.swing.JButton btnSimularCombat;
    private javax.swing.JComboBox<String> comboTipus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAnimacio;
    private javax.swing.JLabel lblGuanyador;
    private javax.swing.JLabel lblResultat;
    private javax.swing.JLabel lblTemps;
    // End of variables declaration//GEN-END:variables
}
