/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.jugador;
import dao.daoGeneric;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author AluCiclesGS1
 */
public class DialogEditarJugador extends javax.swing.JDialog {

    private jugador jugador;
    
    /**
     * Creates new form DialogEditarJugador
     */
    public DialogEditarJugador(java.awt.Frame parent, boolean modal, jugador j) {
        super(parent, modal);
        initComponents();
        this.jugador = j;
        
        TextFieldNom.setText(j.getNom());
        TextFieldNivell.setText(String.valueOf(j.getNivell()));
        TextFieldOr.setText(String.valueOf(j.getOro()));
        TextFieldCopes.setText(String.valueOf(j.getCopes()));
        TextFieldGemes.setText(String.valueOf(j.getGemes())); 
    }

    DialogEditarJugador(principal aThis, boolean b, jugador j) {
        this((java.awt.Frame) aThis, b, j);
    }

    private DialogEditarJugador(JFrame jFrame, boolean b) {
        super(jFrame, b);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        TextFieldCopes1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextFieldNivell = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextFieldOr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextFieldCopes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextFieldGemes = new javax.swing.JTextField();
        BotoGuardarJugador = new javax.swing.JButton();
        BotoCancelar = new javax.swing.JButton();

        jLabel6.setText("Copes");

        TextFieldCopes1.setText("Copes");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Editar jugador");

        jLabel2.setText("Nom");

        TextFieldNom.setText("Nom");

        jLabel3.setText("Nivell");

        TextFieldNivell.setText("Nivell");

        jLabel4.setText("Or");

        TextFieldOr.setText("Or");

        jLabel5.setText("Copes");

        TextFieldCopes.setText("Copes");

        jLabel7.setText("Gemes");

        TextFieldGemes.setText("Gemes");
        TextFieldGemes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldGemesActionPerformed(evt);
            }
        });

        BotoGuardarJugador.setText("Guardar");
        BotoGuardarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoGuardarJugadorActionPerformed(evt);
            }
        });

        BotoCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotoGuardarJugador)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldNivell, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldNom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldOr)
                            .addComponent(TextFieldCopes, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(TextFieldGemes, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(BotoCancelar)))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextFieldNivell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextFieldOr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextFieldCopes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldGemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotoGuardarJugador)
                    .addComponent(BotoCancelar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldGemesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldGemesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldGemesActionPerformed

    private void BotoGuardarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoGuardarJugadorActionPerformed
        jugador.setNom(TextFieldNom.getText());
        jugador.setNivell(Integer.parseInt(TextFieldNivell.getText()));
        jugador.setOro(Integer.parseInt(TextFieldOr.getText()));
        jugador.setCopes(Integer.parseInt(TextFieldCopes.getText()));
        jugador.setGemes(Integer.parseInt(TextFieldGemes.getText()));
        
        daoGeneric.getInstance().updateJugador(jugador);
        JOptionPane.showMessageDialog(this, "Jugador actualitzat");
        this.dispose();
    }//GEN-LAST:event_BotoGuardarJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogEditarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogEditarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogEditarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEditarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogEditarJugador dialog = new DialogEditarJugador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotoCancelar;
    private javax.swing.JButton BotoGuardarJugador;
    private javax.swing.JTextField TextFieldCopes;
    private javax.swing.JTextField TextFieldCopes1;
    private javax.swing.JTextField TextFieldGemes;
    private javax.swing.JTextField TextFieldNivell;
    private javax.swing.JTextField TextFieldNom;
    private javax.swing.JTextField TextFieldOr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
