/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.jugador;
import dao.daoGeneric;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AluCiclesGS1
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextCopes = new javax.swing.JTextField();
        TextNivell = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextGemes = new javax.swing.JTextField();
        TextOr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BotoCrear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaulaJugadors = new javax.swing.JTable();
        BotoLlistarJugadors = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        IdJugadorABorrar = new javax.swing.JTextField();
        BotoEsborrarJugador = new javax.swing.JButton();

        jTextField4.setText("jTextField1");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nivell");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom");

        TextNom.setText("Nom");
        TextNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomActionPerformed(evt);
            }
        });

        jLabel2.setText("Copes");

        TextCopes.setText("Copes");
        TextCopes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCopesActionPerformed(evt);
            }
        });

        TextNivell.setText("Nivell");
        TextNivell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNivellActionPerformed(evt);
            }
        });

        jLabel3.setText("Nivell");

        jLabel5.setText("Gemes");

        TextGemes.setText("Gemes");
        TextGemes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextGemesActionPerformed(evt);
            }
        });

        TextOr.setText("Or");
        TextOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextOrActionPerformed(evt);
            }
        });

        jLabel6.setText("Or");

        BotoCrear.setLabel("Crear Jugador");
        BotoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoCrearActionPerformed(evt);
            }
        });

        TaulaJugadors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Copes", "Nivell", "Gemes", "Or"
            }
        ));
        jScrollPane1.setViewportView(TaulaJugadors);

        BotoLlistarJugadors.setText("Llistat Jugadors");
        BotoLlistarJugadors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoLlistarJugadorsActionPerformed(evt);
            }
        });

        jLabel7.setText("Eliminar un jugador");

        IdJugadorABorrar.setText("id jugador");
        IdJugadorABorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdJugadorABorrarActionPerformed(evt);
            }
        });

        BotoEsborrarJugador.setText("Esborrar");
        BotoEsborrarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoEsborrarJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(519, 519, 519)
                .addComponent(BotoLlistarJugadors)
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(IdJugadorABorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotoEsborrarJugador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(TextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TextCopes, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TextNivell, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TextGemes, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TextOr, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotoCrear))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextCopes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(TextNivell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextGemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextOr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotoCrear)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotoLlistarJugadors)
                            .addComponent(jLabel7)
                            .addComponent(IdJugadorABorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotoEsborrarJugador)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomActionPerformed

    private void TextCopesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCopesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCopesActionPerformed

    private void TextNivellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNivellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNivellActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void TextGemesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextGemesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextGemesActionPerformed

    private void TextOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextOrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextOrActionPerformed

    private void BotoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoCrearActionPerformed
        jugador jug1 = new jugador();
        jug1.setNom(TextNom.getText());
        jug1.setCopes(Integer.parseInt(TextCopes.getText()));
        jug1.setGemes(Integer.parseInt(TextGemes.getText()));
        jug1.setOro(Integer.parseInt(TextOr.getText()));
        jug1.setNivell(Integer.parseInt(TextNivell.getText()));
        
        daoGeneric.getInstance().create(jug1);  
    }//GEN-LAST:event_BotoCrearActionPerformed

    private void BotoLlistarJugadorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoLlistarJugadorsActionPerformed
        List llista = (List) daoGeneric.getInstance().readJugador();
        DefaultTableModel model = (DefaultTableModel) TaulaJugadors.getModel();
        model.setRowCount(0);
        for (int i = 0; i < llista.size(); i++) {
            
            jugador jug = (jugador) llista.get(i);
            //System.out.println(jug.getNom());
            Vector oneRow = new Vector();
            oneRow.add(Integer.toString(jug.getId()));
            oneRow.add(jug.getNom());
            oneRow.add(Integer.toString(jug.getCopes()));
            oneRow.add(Integer.toString(jug.getNivell()));
            oneRow.add(Integer.toString(jug.getGemes()));
            oneRow.add(Integer.toString(jug.getOro()));
            //oneRow.add(jug.getClan());
            model.addRow(oneRow);
            
        }
        
        TaulaJugadors.setModel(model);
    }//GEN-LAST:event_BotoLlistarJugadorsActionPerformed

    private void IdJugadorABorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdJugadorABorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdJugadorABorrarActionPerformed

    private void BotoEsborrarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoEsborrarJugadorActionPerformed
        daoGeneric.getInstance().delete(Integer.parseInt(IdJugadorABorrar.getText()));
    }//GEN-LAST:event_BotoEsborrarJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotoCrear;
    private javax.swing.JButton BotoEsborrarJugador;
    private javax.swing.JButton BotoLlistarJugadors;
    private javax.swing.JTextField IdJugadorABorrar;
    private javax.swing.JTable TaulaJugadors;
    private javax.swing.JTextField TextCopes;
    private javax.swing.JTextField TextGemes;
    private javax.swing.JTextField TextNivell;
    private javax.swing.JTextField TextNom;
    private javax.swing.JTextField TextOr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
